package osgi.web.models;

// Generated 2015-10-17 20:45:21 by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * TbAccount generated by hbm2java
 */
public class TbAccount  {

	private BigDecimal id;
	private String account;
	
	private String name;
	private String role;
	private String phone;
	private String email;
	private int securitylevel;
	private String depart;

	

	@Override
	public String toString() {
		return "TbAccount [id=" + id + ", account=" + account + ", name="
				+ name + ", role=" + role + ", phone=" + phone + ", email="
				+ email + ", securitylevel=" + securitylevel + ", depart="
				+ depart + "]";
	}

	public String getDepart() {
		return depart;
	}

	public void setDepart(String depart) {
		this.depart = depart;
	}

	public TbAccount() {
	}

	public TbAccount(BigDecimal id, String account, String role) {
		this.id = id;
		this.account = account;
		this.role = role;
	}

	public TbAccount(BigDecimal id, String account, String name, String role,
			String phone, String email, int securitylevel) {
		this.id = id;
		this.account = account;
		this.name = name;
		this.role = role;
		this.phone = phone;
		this.email = email;
		this.securitylevel = securitylevel;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public int getSecuritylevel() {
		return this.securitylevel;
	}

	public void setSecuritylevel(int securitylevel) {
		this.securitylevel = securitylevel;
	}

}
