package osgi.web.models;

// Generated 2015-10-17 20:45:21 by Hibernate Tools 4.3.1

/**
 * TbApproval generated by hbm2java
 */
public class TbApproval  {

	private TbApprovalId id;

	public TbApproval() {
	}

	public TbApproval(TbApprovalId id) {
		this.id = id;
	}

	public TbApprovalId getId() {
		return this.id;
	}

	public void setId(TbApprovalId id) {
		this.id = id;
	}

}
