package osgi.web.models;

// Generated 2015-10-17 20:45:21 by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * TbApprovalId generated by hbm2java
 */
public class TbApprovalId {

	private String approver;
	private String approveres;
	private String memo;
	private Serializable tmapprove;
	private BigDecimal prodId;

	public TbApprovalId() {
	}

	public TbApprovalId(String approver, String approveres, String memo,
			Serializable tmapprove, BigDecimal prodId) {
		this.approver = approver;
		this.approveres = approveres;
		this.memo = memo;
		this.tmapprove = tmapprove;
		this.prodId = prodId;
	}

	public String getApprover() {
		return this.approver;
	}

	public void setApprover(String approver) {
		this.approver = approver;
	}

	public String getApproveres() {
		return this.approveres;
	}

	public void setApproveres(String approveres) {
		this.approveres = approveres;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public Serializable getTmapprove() {
		return this.tmapprove;
	}

	public void setTmapprove(Serializable tmapprove) {
		this.tmapprove = tmapprove;
	}

	public BigDecimal getProdId() {
		return this.prodId;
	}

	public void setProdId(BigDecimal prodId) {
		this.prodId = prodId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbApprovalId))
			return false;
		TbApprovalId castOther = (TbApprovalId) other;

		return ((this.getApprover() == castOther.getApprover()) || (this
				.getApprover() != null && castOther.getApprover() != null && this
				.getApprover().equals(castOther.getApprover())))
				&& ((this.getApproveres() == castOther.getApproveres()) || (this
						.getApproveres() != null
						&& castOther.getApproveres() != null && this
						.getApproveres().equals(castOther.getApproveres())))
				&& ((this.getMemo() == castOther.getMemo()) || (this.getMemo() != null
						&& castOther.getMemo() != null && this.getMemo()
						.equals(castOther.getMemo())))
				&& ((this.getTmapprove() == castOther.getTmapprove()) || (this
						.getTmapprove() != null
						&& castOther.getTmapprove() != null && this
						.getTmapprove().equals(castOther.getTmapprove())))
				&& ((this.getProdId() == castOther.getProdId()) || (this
						.getProdId() != null && castOther.getProdId() != null && this
						.getProdId().equals(castOther.getProdId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getApprover() == null ? 0 : this.getApprover().hashCode());
		result = 37
				* result
				+ (getApproveres() == null ? 0 : this.getApproveres()
						.hashCode());
		result = 37 * result
				+ (getMemo() == null ? 0 : this.getMemo().hashCode());
		result = 37 * result
				+ (getTmapprove() == null ? 0 : this.getTmapprove().hashCode());
		result = 37 * result
				+ (getProdId() == null ? 0 : this.getProdId().hashCode());
		return result;
	}

}
